### PR TITLE
Added support for PLUGINS_FILE

### PR DESCRIPTION
**Pull request by pianwan**
The PLUGINS_FILE env var now works for itzg/mc-proxy image.

### CODE REVIEW

**Review by itzg — COMMENTED** [review]
Thanks for bringing that over. Do you mind also adding a brief description of the var to https://github.com/itzg/docker-mc-proxy#environment-settings ?

**Comment by pianwan** [comment]
> Thanks for bringing that over. Do you mind also adding a brief description of the var to https://github.com/itzg/docker-mc-proxy#environment-settings ?

Thanks for your reply. I’ll go ahead and add a brief description of the variable shortly.

**Comment by pianwan** [comment]
Done. Plz use dd8b3b2.

**Review by itzg — APPROVED** [review]

**Comment by itzg** [comment]
Included in this build https://github.com/itzg/docker-mc-proxy/actions/runs/12257152466

**Pull request merged**
